apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ss
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/ss/overlays/development
    repoURL: https://github.com/stephanie-cy/sssad-gitops
    targetRevision: main
  destination:
    namespace: adsaw
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
